### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by JodexIndustries** [VoxelHax/OpenBukloit#1]
[README.md](https://github.com/VoxelHax/OpenBukloit/files/8789113/README.md)
[README_RU.md](https://github.com/VoxelHax/OpenBukloit/files/8789114/README_RU.md)

**Comment by Rikonardo** [comment]
https://github.com/VoxelHax/OpenBukloit/commit/36d1e28703996462564e986a15a0dc23259e8964 Translations added
