### ISSUE TITLE
Using a different way of hosting

### ISSUE THREAD

**Issue by vaMe69** [VoxelHax/OpenBukloit#27]
So the server I want to use OpenBukloit is a server that is being hosted on server.pro. I put OpenBukloit.jar in /libraries/com/microsoft/azure/msal4j/1.15.0, how can i execute it?

**Comment by wendellmeset** [comment]
OpenBukloit is not a plugin, it is a java injector, you have to inject a backdoor into a plugin, then put that plugin onto your server.pro server.

**Comment by wendellmeset** [comment]
If you need additional help feel free to reopen this issue or start a new one, for now I am closing this issue.
