### ISSUE TITLE
Still wont work on mac.

### ISSUE THREAD

**Issue by wendellmeset** [VoxelHax/OpenBukloit#7]
You get this error.
java.lang.Exception: No JDK release found for mac x86_64

**Comment by Rikonardo** [comment]
I'll try to fix it soon

**Comment by wendellmeset** [comment]
@Rikonardo any luck

**Comment by wendellmeset** [comment]
@Rikonardo ?

**Comment by Rikonardo** [comment]
Added work on this bug to the to-do list for this weekend. I apologize for the long wait, didn't have much free time in November

**Comment by Rikonardo** [comment]
Should be fixed in the new release:
https://github.com/VoxelHax/OpenBukloit/releases/tag/v1.0.8

Let me know if everything works ok, so I can close the issue
